# GENERATED by codegen/generate.py - DO NOT EDIT
from __future__ import annotations

from typing import Literal

from ._helpers import _get_client, _ok

# ── GET ──

def api_root():
    """Api Root"""
    return _ok(_get_client().get("/api/0/"))


def comments_list_comments(issue_id: str, limit: int | None = None, cursor: str | None = None):
    """List Comments"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/issues/{issue_id}/comments/", params=_q or None))


def events_get_event_json(organization_slug: str, issue_id: str, event_id: str):
    """Get Event Json"""
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/issues/{issue_id}/events/{event_id}/json/"))


def events_get_issue_event(issue_id: str, event_id: str):
    """Get Issue Event"""
    return _ok(_get_client().get(f"/api/0/issues/{issue_id}/events/{event_id}/"))


def events_get_latest_issue_event(issue_id: str):
    """Get Latest Issue Event"""
    return _ok(_get_client().get(f"/api/0/issues/{issue_id}/events/latest/"))


def events_get_project_issue_event(organization_slug: str, project_slug: str, event_id: str):
    """Get Project Issue Event"""
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/events/{event_id}/"))


def events_list_issue_event(issue_id: str, limit: int | None = None, cursor: str | None = None):
    """List Issue Event"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/issues/{issue_id}/events/", params=_q or None))


def events_list_project_issue_event(organization_slug: str, project_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Project Issue Event"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/events/", params=_q or None))


def generate_recovery_codes():
    """Generate Recovery Codes"""
    return _ok(_get_client().get("/api/0/generate-recovery-codes/"))


def get_accept_invite(org_user_id: str, token: str):
    """Get Accept Invite"""
    return _ok(_get_client().get(f"/api/0/accept/{org_user_id}/{token}/"))


def get_chunk_upload_info(organization_slug: str):
    """Get Chunk Upload Info"""
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/chunk-upload/"))


def get_embed_error_page(dsn: str, eventId: str, title: str | None = None, subtitle: str | None = None, subtitle2: str | None = None, labelName: str | None = None, labelEmail: str | None = None, labelComments: str | None = None, labelClose: str | None = None, labelSubmit: str | None = None, errorGeneric: str | None = None, errorFormEntry: str | None = None, successMessage: str | None = None, name: str | None = None, email: str | None = None):
    """Get Embed Error Page"""
    _q: dict = {}
    if dsn is not None:
        _q['dsn'] = dsn
    if eventId is not None:
        _q['eventId'] = eventId
    if title is not None:
        _q['title'] = title
    if subtitle is not None:
        _q['subtitle'] = subtitle
    if subtitle2 is not None:
        _q['subtitle2'] = subtitle2
    if labelName is not None:
        _q['labelName'] = labelName
    if labelEmail is not None:
        _q['labelEmail'] = labelEmail
    if labelComments is not None:
        _q['labelComments'] = labelComments
    if labelClose is not None:
        _q['labelClose'] = labelClose
    if labelSubmit is not None:
        _q['labelSubmit'] = labelSubmit
    if errorGeneric is not None:
        _q['errorGeneric'] = errorGeneric
    if errorFormEntry is not None:
        _q['errorFormEntry'] = errorFormEntry
    if successMessage is not None:
        _q['successMessage'] = successMessage
    if name is not None:
        _q['name'] = name
    if email is not None:
        _q['email'] = email
    return _ok(_get_client().get("/api/embed/error-page/", params=_q or None))


def get_log(organization_slug: str, log_id: str):
    """Get Log"""
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/logs/{log_id}/"))


def get_log_stats(organization_slug: str, project: list[int] | None = None, level: list[str] | None = None, service: list[str] | None = None, environment: list[str] | None = None, start: str | None = None, end: str | None = None):
    """Get Log Stats"""
    _q: dict = {}
    if project is not None:
        _q['project'] = project
    if level is not None:
        _q['level'] = level
    if service is not None:
        _q['service'] = service
    if environment is not None:
        _q['environment'] = environment
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/logs/stats/", params=_q or None))


def get_monitor(organization_slug: str, monitor_id: str):
    """Get Monitor"""
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/monitors/{monitor_id}/"))


def get_notifications(user_id: str):
    """Get Notifications"""
    return _ok(_get_client().get(f"/api/0/users/{user_id}/notifications/"))


def get_organization(organization_slug: str):
    """Get Organization"""
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/"))


def get_organization_member(organization_slug: str, member_id: str):
    """Get Organization Member"""
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/members/{member_id}/"))


def get_organization_release_file(organization_slug: str, version: str, file_id: str, project_slug: str):
    """Get Organization Release File"""
    _q: dict = {}
    if project_slug is not None:
        _q['project_slug'] = project_slug
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/releases/{version}/files/{file_id}/", params=_q or None))


def get_project(organization_slug: str, project_slug: str):
    """Get Project"""
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/"))


def get_project_key(organization_slug: str, project_slug: str, key_id: str):
    """Get Project Key"""
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/keys/{key_id}/"))


def get_project_release(organization_slug: str, project_slug: str, version: str):
    """Get Project Release"""
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/releases/{version}/"))


def get_project_release_file(organization_slug: str, project_slug: str, version: str, file_id: str):
    """Get Project Release File"""
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/releases/{version}/files/{file_id}/"))


def get_release(organization_slug: str, version: str):
    """Get Release"""
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/releases/{version}/"))


def get_settings():
    """Get Settings"""
    return _ok(_get_client().get("/api/settings/"))


def get_stripe_subscription(organization_slug: str):
    """Get Stripe Subscription"""
    return _ok(_get_client().get(f"/api/0/stripe/subscriptions/{organization_slug}/"))


def get_team(organization_slug: str, team_slug: str):
    """Get Team"""
    return _ok(_get_client().get(f"/api/0/teams/{organization_slug}/{team_slug}/"))


def get_transaction_group(organization_slug: str, id: str):
    """Get Transaction Group"""
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/transaction-groups/{id}/"))


def get_transaction_trend(organization_slug: str, id: str, start: str | None = None, end: str | None = None):
    """Get Transaction Trend"""
    _q: dict = {}
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/transaction-groups/{id}/trend/", params=_q or None))


def get_user(user_id: str):
    """Get User"""
    return _ok(_get_client().get(f"/api/0/users/{user_id}/"))


def hashes_list_issue_hashes(organization_slug: str, issue_id: str, limit: int | None = None, cursor: str | None = None):
    """List Issue Hashes"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/issues/{issue_id}/hashes/", params=_q or None))


def issues_get_issue(issue_id: str):
    """Get Issue"""
    return _ok(_get_client().get(f"/api/0/issues/{issue_id}/"))


def issues_issue_stats(organization_slug: str, groups: list[int], statsPeriod: Literal['14d', '24h'] | None = None):
    """Retrieve Statistics for a Set of Issues"""
    _q: dict = {}
    if groups is not None:
        _q['groups'] = groups
    if statsPeriod is not None:
        _q['statsPeriod'] = statsPeriod
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/issues-stats/", params=_q or None))


def issues_list_issue_commits(issue_id: str):
    """List Issue Commits"""
    return _ok(_get_client().get(f"/api/0/issues/{issue_id}/commits/"))


def issues_list_issue_tags(issue_id: str, key: str | None = None):
    """List Issue Tags"""
    _q: dict = {}
    if key is not None:
        _q['key'] = key
    return _ok(_get_client().get(f"/api/0/issues/{issue_id}/tags/", params=_q or None))


def issues_list_issues(organization_slug: str, id: list[int] | None = None, start: str | None = None, end: str | None = None, project: list[int] | None = None, environment: list[str] | None = None, query: str | None = None, sort: Literal['last_seen', 'first_seen', 'count', 'priority', '-last_seen', '-first_seen', '-count', '-priority'] | None = None, limit: int | None = None, cursor: str | None = None):
    """List Issues"""
    _q: dict = {}
    if id is not None:
        _q['id'] = id
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    if project is not None:
        _q['project'] = project
    if environment is not None:
        _q['environment'] = environment
    if query is not None:
        _q['query'] = query
    if sort is not None:
        _q['sort'] = sort
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/issues/", params=_q or None))


def issues_list_project_issues(organization_slug: str, project_slug: str, id: list[int] | None = None, start: str | None = None, end: str | None = None, project: list[int] | None = None, environment: list[str] | None = None, query: str | None = None, sort: Literal['last_seen', 'first_seen', 'count', 'priority', '-last_seen', '-first_seen', '-count', '-priority'] | None = None, limit: int | None = None, cursor: str | None = None):
    """List Project Issues"""
    _q: dict = {}
    if id is not None:
        _q['id'] = id
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    if project is not None:
        _q['project'] = project
    if environment is not None:
        _q['environment'] = environment
    if query is not None:
        _q['query'] = query
    if sort is not None:
        _q['sort'] = sort
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/issues/", params=_q or None))


def list_api_tokens(limit: int | None = None, cursor: str | None = None):
    """List Api Tokens"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get("/api/0/api-tokens/", params=_q or None))


def list_commits(organization_slug: str, version: str):
    """List Commits"""
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/releases/{version}/commits/"))


def list_deploys(organization_slug: str, version: str):
    """List Deploys"""
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/releases/{version}/deploys/"))


def list_dsyms(organization_slug: str, project_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Dsyms"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/files/dsyms/", params=_q or None))


def list_emails(user_id: str):
    """List Emails"""
    return _ok(_get_client().get(f"/api/0/users/{user_id}/emails/"))


def list_environment_projects(organization_slug: str, project_slug: str, visibility: Literal['all', 'hidden', 'visible'] | None = None, limit: int | None = None, cursor: str | None = None):
    """List Environment Projects"""
    _q: dict = {}
    if visibility is not None:
        _q['visibility'] = visibility
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/environments/", params=_q or None))


def list_environments(organization_slug: str, visibility: Literal['all', 'hidden', 'visible'] | None = None, limit: int | None = None, cursor: str | None = None):
    """List Environments"""
    _q: dict = {}
    if visibility is not None:
        _q['visibility'] = visibility
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/environments/", params=_q or None))


def list_log_resources(organization_slug: str, resource_type: str | None = None):
    """List Log Resources"""
    _q: dict = {}
    if resource_type is not None:
        _q['resource_type'] = resource_type
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/logs/resources/", params=_q or None))


def list_logs(organization_slug: str, project: list[int] | None = None, level: list[str] | None = None, service: str | None = None, environment: str | None = None, host: str | None = None, traceId: str | None = None, query: str | None = None, start: str | None = None, end: str | None = None, cursor: str | None = None, limit: int | None = None):
    """List Logs"""
    _q: dict = {}
    if project is not None:
        _q['project'] = project
    if level is not None:
        _q['level'] = level
    if service is not None:
        _q['service'] = service
    if environment is not None:
        _q['environment'] = environment
    if host is not None:
        _q['host'] = host
    if traceId is not None:
        _q['traceId'] = traceId
    if query is not None:
        _q['query'] = query
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    if cursor is not None:
        _q['cursor'] = cursor
    if limit is not None:
        _q['limit'] = limit
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/logs/", params=_q or None))


def list_monitor_checks(organization_slug: str, monitor_id: str, is_change: bool | None = None, limit: int | None = None, cursor: str | None = None):
    """List Monitor Checks"""
    _q: dict = {}
    if is_change is not None:
        _q['is_change'] = is_change
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/monitors/{monitor_id}/checks/", params=_q or None))


def list_monitors(organization_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Monitors"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/monitors/", params=_q or None))


def list_n_plus_one_patterns(organization_slug: str, start: str | None = None, end: str | None = None, project: list[int] | None = None, op: str | None = None, threshold: float | None = None, limit: int | None = None):
    """List N Plus One Patterns"""
    _q: dict = {}
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    if project is not None:
        _q['project'] = project
    if op is not None:
        _q['op'] = op
    if threshold is not None:
        _q['threshold'] = threshold
    if limit is not None:
        _q['limit'] = limit
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/n-plus-one/", params=_q or None))


def list_organization_members(organization_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Organization Members"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/members/", params=_q or None))


def list_organization_projects(organization_slug: str, query: str | None = None, limit: int | None = None, cursor: str | None = None):
    """List Organization Projects"""
    _q: dict = {}
    if query is not None:
        _q['query'] = query
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/projects/", params=_q or None))


def list_organizations(owner: bool | None = None, query: str | None = None, sortBy: str | None = None, limit: int | None = None, cursor: str | None = None):
    """List Organizations"""
    _q: dict = {}
    if owner is not None:
        _q['owner'] = owner
    if query is not None:
        _q['query'] = query
    if sortBy is not None:
        _q['sortBy'] = sortBy
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get("/api/0/organizations/", params=_q or None))


def list_project_alerts(organization_slug: str, project_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Project Alerts"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/alerts/", params=_q or None))


def list_project_keys(organization_slug: str, project_slug: str, status: str | None = None, limit: int | None = None, cursor: str | None = None):
    """List Project Keys"""
    _q: dict = {}
    if status is not None:
        _q['status'] = status
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/keys/", params=_q or None))


def list_project_release_files(organization_slug: str, project_slug: str, version: str, limit: int | None = None, cursor: str | None = None):
    """List Project Release Files"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/releases/{version}/files/", params=_q or None))


def list_project_releases(organization_slug: str, project_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Project Releases"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/releases/", params=_q or None))


def list_project_teams(organization_slug: str, project_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Project Teams"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/projects/{organization_slug}/{project_slug}/teams/", params=_q or None))


def list_projects(limit: int | None = None, cursor: str | None = None):
    """List Projects"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get("/api/0/projects/", params=_q or None))


def list_release_files(organization_slug: str, version: str, limit: int | None = None, cursor: str | None = None):
    """List Release Files"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/releases/{version}/files/", params=_q or None))


def list_releases(organization_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Releases"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/releases/", params=_q or None))


def list_repositories(organization_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Repositories"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/repos/", params=_q or None))


def list_span_groups(organization_slug: str, start: str | None = None, end: str | None = None, project: list[int] | None = None, op: str | None = None, sort: Literal['total_time', '-total_time', 'avg_duration', '-avg_duration', 'count', '-count'] | None = None, limit: int | None = None):
    """List Span Groups"""
    _q: dict = {}
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    if project is not None:
        _q['project'] = project
    if op is not None:
        _q['op'] = op
    if sort is not None:
        _q['sort'] = sort
    if limit is not None:
        _q['limit'] = limit
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/span-groups/", params=_q or None))


def list_status_pages(organization_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Status Pages"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/status-pages/", params=_q or None))


def list_stripe_products():
    """List Stripe Products"""
    return _ok(_get_client().get("/api/0/stripe/products/"))


def list_team_organization_members(organization_slug: str, team_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Team Organization Members"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/teams/{organization_slug}/{team_slug}/members/", params=_q or None))


def list_team_projects(organization_slug: str, team_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Team Projects"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/teams/{organization_slug}/{team_slug}/projects/", params=_q or None))


def list_teams(organization_slug: str, limit: int | None = None, cursor: str | None = None):
    """List Teams"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/teams/", params=_q or None))


def list_transaction_groups(organization_slug: str, start: str | None = None, end: str | None = None, sort: Literal['created', '-created', 'avg_duration', '-avg_duration', 'count', '-count'] | None = None, project: list[int] | None = None, query: str | None = None, limit: int | None = None, cursor: str | None = None):
    """List Transaction Groups"""
    _q: dict = {}
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    if sort is not None:
        _q['sort'] = sort
    if project is not None:
        _q['project'] = project
    if query is not None:
        _q['query'] = query
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/transaction-groups/", params=_q or None))


def list_transaction_spans(organization_slug: str, id: str, start: str | None = None, end: str | None = None):
    """List Transaction Spans"""
    _q: dict = {}
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/transaction-groups/{id}/spans/", params=_q or None))


def list_users(limit: int | None = None, cursor: str | None = None):
    """List Users"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get("/api/0/users/", params=_q or None))


def setup_wizard():
    """Setup Wizard"""
    return _ok(_get_client().get("/api/0/wizard/"))


def setup_wizard_hash(wizard_hash: str, auth: str | None = None):
    """Setup Wizard Hash"""
    _q: dict = {}
    if auth is not None:
        _q['auth'] = auth
    return _ok(_get_client().get(f"/api/0/wizard/{wizard_hash}/", params=_q or None))


def stats_v2(organization_slug: str, category: Literal['error', 'transaction'], field: Literal['sum(quantity)', 'sum(times_seen)'], start: str, end: str, interval: Literal['1d', '1h', '1m'] | None = None, project: list[int] | None = None):
    """Stats V2"""
    _q: dict = {}
    if category is not None:
        _q['category'] = category
    if field is not None:
        _q['field'] = field
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    if interval is not None:
        _q['interval'] = interval
    if project is not None:
        _q['project'] = project
    return _ok(_get_client().get(f"/api/0/organizations/{organization_slug}/stats_v2/", params=_q or None))


def subscription_events_count_daily(organization_slug: str):
    """Subscription Events Count Daily"""
    return _ok(_get_client().get(f"/api/0/stripe/subscriptions/{organization_slug}/events_count/daily/"))


def subscription_events_count_for_period(organization_slug: str, periods_ago: int | None = None):
    """Subscription Events Count For Period"""
    _q: dict = {}
    if periods_ago is not None:
        _q['periods_ago'] = periods_ago
    return _ok(_get_client().get(f"/api/0/stripe/subscriptions/{organization_slug}/events_count/period/", params=_q or None))


def user_notification_alerts(user_id: str):
    """User Notification Alerts"""
    return _ok(_get_client().get(f"/api/0/users/{user_id}/notifications/alerts/"))


def user_reports_list_user_reports(issue_id: str, limit: int | None = None, cursor: str | None = None):
    """List User Reports"""
    _q: dict = {}
    if limit is not None:
        _q['limit'] = limit
    if cursor is not None:
        _q['cursor'] = cursor
    return _ok(_get_client().get(f"/api/0/issues/{issue_id}/user-reports/", params=_q or None))


# ── POST ──

def accept_invite(org_user_id: str, token: str, acceptInvite: bool):
    """Accept Invite"""
    _b: dict = {}
    if acceptInvite is None:
        raise ValueError("Required request field acceptInvite cannot be null")
    _b['acceptInvite'] = acceptInvite
    return _ok(_get_client().post(f"/api/0/accept/{org_user_id}/{token}/", _b))


def add_member_to_team(organization_slug: str, member_id: str, team_slug: str):
    """Add Member To Team"""
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/members/{member_id}/teams/{team_slug}/", None))


def add_team_to_project(organization_slug: str, project_slug: str, team_slug: str):
    """Add Team To Project"""
    return _ok(_get_client().post(f"/api/0/projects/{organization_slug}/{project_slug}/teams/{team_slug}/", None))


def artifact_bundle_assemble(organization_slug: str, checksum: str, chunks: list[str], projects: list[str], version: str | None = None):
    """Artifact Bundle Assemble"""
    _b: dict = {}
    if checksum is None:
        raise ValueError("Required request field checksum cannot be null")
    _b['checksum'] = checksum
    if chunks is None:
        raise ValueError("Required request field chunks cannot be null")
    _b['chunks'] = chunks
    if projects is None:
        raise ValueError("Required request field projects cannot be null")
    _b['projects'] = projects
    if version is not None:
        _b['version'] = version
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/artifactbundle/assemble/", _b))


def assemble_release(organization_slug: str, version: str, checksum: str, chunks: list[str]):
    """Assemble Release"""
    _b: dict = {}
    if checksum is None:
        raise ValueError("Required request field checksum cannot be null")
    _b['checksum'] = checksum
    if chunks is None:
        raise ValueError("Required request field chunks cannot be null")
    _b['chunks'] = chunks
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/releases/{version}/assemble/", _b))


def chunk_upload(organization_slug: str, body: dict | list):
    """Chunk Upload"""
    if body is None:
        raise ValueError("Required request body cannot be null")
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/chunk-upload/", body))


def comments_add_comment(issue_id: str, data: dict):
    """Add Comment"""
    _b: dict = {}
    if data is None:
        raise ValueError("Required request field data cannot be null")
    _b['data'] = data
    return _ok(_get_client().post(f"/api/0/issues/{issue_id}/comments/", _b))


def create_api_token(scopes: int, label: str | None = None):
    """Create Api Token"""
    _b: dict = {}
    if scopes is None:
        raise ValueError("Required request field scopes cannot be null")
    _b['scopes'] = scopes
    if label is not None:
        _b['label'] = label
    return _ok(_get_client().post("/api/0/api-tokens/", _b))


def create_commits(organization_slug: str, version: str, body: dict | list):
    """Create Commits"""
    if body is None:
        raise ValueError("Required request body cannot be null")
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/releases/{version}/commits/", body))


def create_deploy(organization_slug: str, version: str, environment: str, url: str | None = None, dateStarted: str | None = None, dateFinished: str | None = None):
    """Create Deploy"""
    _b: dict = {}
    if environment is None:
        raise ValueError("Required request field environment cannot be null")
    _b['environment'] = environment
    if url is not None:
        _b['url'] = url
    if dateStarted is not None:
        _b['dateStarted'] = dateStarted
    if dateFinished is not None:
        _b['dateFinished'] = dateFinished
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/releases/{version}/deploys/", _b))


def create_email(user_id: str, email: str):
    """Create Email"""
    _b: dict = {}
    if email is None:
        raise ValueError("Required request field email cannot be null")
    _b['email'] = email
    return _ok(_get_client().post(f"/api/0/users/{user_id}/emails/", _b))


def create_monitor(organization_slug: str, expectedBody: str, expectedStatus: int | None, timeout: int | None, name: str, project: str | None = None, monitorType: str | None = None, url: str | None = None, interval: int | None = None):
    """Create Monitor"""
    _b: dict = {}
    if expectedBody is None:
        raise ValueError("Required request field expectedBody cannot be null")
    _b['expectedBody'] = expectedBody
    _b['expectedStatus'] = expectedStatus
    _b['timeout'] = timeout
    if name is None:
        raise ValueError("Required request field name cannot be null")
    _b['name'] = name
    if project is not None:
        _b['project'] = project
    if monitorType is not None:
        _b['monitorType'] = monitorType
    if url is not None:
        _b['url'] = url
    if interval is not None:
        _b['interval'] = interval
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/monitors/", _b))


def create_organization(name: str):
    """Create Organization"""
    _b: dict = {}
    if name is None:
        raise ValueError("Required request field name cannot be null")
    _b['name'] = name
    return _ok(_get_client().post("/api/0/organizations/", _b))


def create_organization_member(organization_slug: str, orgRole: Literal['member', 'admin', 'manager', 'owner'], email: str, teamRoles: list[dict] | None = None, sendInvite: bool | None = None, reinvite: bool | None = None):
    """Create Organization Member"""
    _b: dict = {}
    if orgRole is None:
        raise ValueError("Required request field orgRole cannot be null")
    _b['orgRole'] = orgRole
    if email is None:
        raise ValueError("Required request field email cannot be null")
    _b['email'] = email
    if teamRoles is not None:
        _b['teamRoles'] = teamRoles
    if sendInvite is not None:
        _b['sendInvite'] = sendInvite
    if reinvite is not None:
        _b['reinvite'] = reinvite
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/members/", _b))


def create_project(organization_slug: str, team_slug: str, name: str, slug: str | None = None, platform: str | None = None, eventThrottleRate: int | None = None):
    """Create Project"""
    _b: dict = {}
    if name is None:
        raise ValueError("Required request field name cannot be null")
    _b['name'] = name
    if slug is not None:
        _b['slug'] = slug
    if platform is not None:
        _b['platform'] = platform
    if eventThrottleRate is not None:
        _b['eventThrottleRate'] = eventThrottleRate
    return _ok(_get_client().post(f"/api/0/teams/{organization_slug}/{team_slug}/projects/", _b))


def create_project_alert(organization_slug: str, project_slug: str, name: str | None = None, alertRecipients: list[dict] | None = None, timespanMinutes: int | None = None, quantity: int | None = None, uptime: bool | None = None):
    """Create Project Alert"""
    _b: dict = {}
    if name is not None:
        _b['name'] = name
    if alertRecipients is not None:
        _b['alertRecipients'] = alertRecipients
    if timespanMinutes is not None:
        _b['timespanMinutes'] = timespanMinutes
    if quantity is not None:
        _b['quantity'] = quantity
    if uptime is not None:
        _b['uptime'] = uptime
    return _ok(_get_client().post(f"/api/0/projects/{organization_slug}/{project_slug}/alerts/", _b))


def create_project_key(organization_slug: str, project_slug: str, name: str | None = None, rateLimit: dict | None = None):
    """Create Project Key"""
    _b: dict = {}
    if name is not None:
        _b['name'] = name
    if rateLimit is not None:
        _b['rateLimit'] = rateLimit
    return _ok(_get_client().post(f"/api/0/projects/{organization_slug}/{project_slug}/keys/", _b))


def create_project_release(organization_slug: str, project_slug: str, version: str, ref: str | None = None, dateReleased: str | None = None):
    """Create Project Release"""
    _b: dict = {}
    if version is None:
        raise ValueError("Required request field version cannot be null")
    _b['version'] = version
    if ref is not None:
        _b['ref'] = ref
    if dateReleased is not None:
        _b['dateReleased'] = dateReleased
    return _ok(_get_client().post(f"/api/0/projects/{organization_slug}/{project_slug}/releases/", _b))


def create_release(organization_slug: str, version: str, projects: list[str], ref: str | None = None, dateReleased: str | None = None):
    """Create Release"""
    _b: dict = {}
    if version is None:
        raise ValueError("Required request field version cannot be null")
    _b['version'] = version
    if projects is None:
        raise ValueError("Required request field projects cannot be null")
    _b['projects'] = projects
    if ref is not None:
        _b['ref'] = ref
    if dateReleased is not None:
        _b['dateReleased'] = dateReleased
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/releases/", _b))


def create_repository(organization_slug: str, name: str, url: str | None = None, provider: dict | None = None):
    """Create Repository"""
    _b: dict = {}
    if name is None:
        raise ValueError("Required request field name cannot be null")
    _b['name'] = name
    if url is not None:
        _b['url'] = url
    if provider is not None:
        _b['provider'] = provider
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/repos/", _b))


def create_status_page(organization_slug: str, name: str, isPublic: bool | None = None):
    """Create Status Page"""
    _b: dict = {}
    if name is None:
        raise ValueError("Required request field name cannot be null")
    _b['name'] = name
    if isPublic is not None:
        _b['isPublic'] = isPublic
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/status-pages/", _b))


def create_stripe_session(organization_slug: str, price: str):
    """Create Stripe Session"""
    _b: dict = {}
    if price is None:
        raise ValueError("Required request field price cannot be null")
    _b['price'] = price
    return _ok(_get_client().post(f"/api/0/stripe/organizations/{organization_slug}/create-stripe-subscription-checkout/", _b))


def create_team(organization_slug: str, slug: str):
    """Create Team"""
    _b: dict = {}
    if slug is None:
        raise ValueError("Required request field slug cannot be null")
    _b['slug'] = slug
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/teams/", _b))


def difs_assemble_api(organization_slug: str, project_slug: str, body: dict | list):
    """Difs Assemble Api"""
    if body is None:
        raise ValueError("Required request body cannot be null")
    return _ok(_get_client().post(f"/api/0/projects/{organization_slug}/{project_slug}/files/difs/assemble/", body))


def dsyms(organization_slug: str, project_slug: str, body: dict | list):
    """Dsyms"""
    if body is None:
        raise ValueError("Required request body cannot be null")
    return _ok(_get_client().post(f"/api/0/projects/{organization_slug}/{project_slug}/files/dsyms/", body))


def event_security(project_id: str, csp_report: dict):
    """Event Security"""
    _b: dict = {}
    if csp_report is None:
        raise ValueError("Required request field csp-report cannot be null")
    _b['csp-report'] = csp_report
    return _ok(_get_client().post(f"/api/{project_id}/security/", _b))


def event_store(project_id: str, event_id: str, platform: str | None = None, errors: list[dict] | None = None, timestamp: str | None = None, level: str | None = None, logentry: dict | None = None, logger: str | None = None, transaction: str | None = None, server_name: str | None = None, release: str | None = None, dist: str | None = None, tags: list[list[str]] | None = None, environment: str | None = None, modules: dict | None = None, extra: dict | None = None, fingerprint: list[str] | None = None, exception: dict | None = None, threads: dict | None = None, message: str | None = None, template: dict | None = None, breadcrumbs: dict | None = None, sdk: dict | None = None, request: dict | None = None, contexts: dict | None = None, user: dict | None = None, debug_meta: dict | None = None):
    """Event Store"""
    _b: dict = {}
    if event_id is None:
        raise ValueError("Required request field event_id cannot be null")
    _b['event_id'] = event_id
    if platform is not None:
        _b['platform'] = platform
    if errors is not None:
        _b['errors'] = errors
    if timestamp is not None:
        _b['timestamp'] = timestamp
    if level is not None:
        _b['level'] = level
    if logentry is not None:
        _b['logentry'] = logentry
    if logger is not None:
        _b['logger'] = logger
    if transaction is not None:
        _b['transaction'] = transaction
    if server_name is not None:
        _b['server_name'] = server_name
    if release is not None:
        _b['release'] = release
    if dist is not None:
        _b['dist'] = dist
    if tags is not None:
        _b['tags'] = tags
    if environment is not None:
        _b['environment'] = environment
    if modules is not None:
        _b['modules'] = modules
    if extra is not None:
        _b['extra'] = extra
    if fingerprint is not None:
        _b['fingerprint'] = fingerprint
    if exception is not None:
        _b['exception'] = exception
    if threads is not None:
        _b['threads'] = threads
    if message is not None:
        _b['message'] = message
    if template is not None:
        _b['template'] = template
    if breadcrumbs is not None:
        _b['breadcrumbs'] = breadcrumbs
    if sdk is not None:
        _b['sdk'] = sdk
    if request is not None:
        _b['request'] = request
    if contexts is not None:
        _b['contexts'] = contexts
    if user is not None:
        _b['user'] = user
    if debug_meta is not None:
        _b['debug_meta'] = debug_meta
    return _ok(_get_client().post(f"/api/{project_id}/store/", _b))


def heartbeat_check(organization_slug: str, endpoint_id: str):
    """Heartbeat Check"""
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/heartbeat_check/{endpoint_id}/", None))


def importer(url: str, authToken: str, organizationSlug: str):
    """Importer"""
    _b: dict = {}
    if url is None:
        raise ValueError("Required request field url cannot be null")
    _b['url'] = url
    if authToken is None:
        raise ValueError("Required request field authToken cannot be null")
    _b['authToken'] = authToken
    if organizationSlug is None:
        raise ValueError("Required request field organizationSlug cannot be null")
    _b['organizationSlug'] = organizationSlug
    return _ok(_get_client().post("/api/0/import/", _b))


def project_reprocessing(organization_slug: str, project_slug: str):
    """Project Reprocessing"""
    return _ok(_get_client().post(f"/api/0/projects/{organization_slug}/{project_slug}/reprocessing/", None))


def send_confirm_email(user_id: str, email: str):
    """Send Confirm Email"""
    _b: dict = {}
    if email is None:
        raise ValueError("Required request field email cannot be null")
    _b['email'] = email
    return _ok(_get_client().post(f"/api/0/users/{user_id}/emails/confirm/", _b))


def set_organization_owner(organization_slug: str, member_id: str):
    """Set Organization Owner"""
    return _ok(_get_client().post(f"/api/0/organizations/{organization_slug}/members/{member_id}/set_owner/", None))


def set_recovery_codes(code: str):
    """Set Recovery Codes"""
    _b: dict = {}
    if code is None:
        raise ValueError("Required request field code cannot be null")
    _b['code'] = code
    return _ok(_get_client().post("/api/0/generate-recovery-codes/", _b))


def setup_wizard_set_token(hash: str):
    """Setup Wizard Set Token"""
    _b: dict = {}
    if hash is None:
        raise ValueError("Required request field hash cannot be null")
    _b['hash'] = hash
    return _ok(_get_client().post("/api/0/wizard-set-token/", _b))


def stripe_billing_portal_session(organization_slug: str):
    """Stripe Billing Portal Session"""
    return _ok(_get_client().post(f"/api/0/stripe/organizations/{organization_slug}/create-billing-portal/", None))


def stripe_create_subscription(price: str, organization: str):
    """Stripe Create Subscription"""
    _b: dict = {}
    if price is None:
        raise ValueError("Required request field price cannot be null")
    _b['price'] = price
    if organization is None:
        raise ValueError("Required request field organization cannot be null")
    _b['organization'] = organization
    return _ok(_get_client().post("/api/0/stripe/subscriptions/", _b))


def submit_embed_error_page(dsn: str, eventId: str, body: dict | list, title: str | None = None, subtitle: str | None = None, subtitle2: str | None = None, labelName: str | None = None, labelEmail: str | None = None, labelComments: str | None = None, labelClose: str | None = None, labelSubmit: str | None = None, errorGeneric: str | None = None, errorFormEntry: str | None = None, successMessage: str | None = None, name: str | None = None, email: str | None = None):
    """Submit Embed Error Page"""
    _q: dict = {}
    if dsn is not None:
        _q['dsn'] = dsn
    if eventId is not None:
        _q['eventId'] = eventId
    if title is not None:
        _q['title'] = title
    if subtitle is not None:
        _q['subtitle'] = subtitle
    if subtitle2 is not None:
        _q['subtitle2'] = subtitle2
    if labelName is not None:
        _q['labelName'] = labelName
    if labelEmail is not None:
        _q['labelEmail'] = labelEmail
    if labelComments is not None:
        _q['labelComments'] = labelComments
    if labelClose is not None:
        _q['labelClose'] = labelClose
    if labelSubmit is not None:
        _q['labelSubmit'] = labelSubmit
    if errorGeneric is not None:
        _q['errorGeneric'] = errorGeneric
    if errorFormEntry is not None:
        _q['errorFormEntry'] = errorFormEntry
    if successMessage is not None:
        _q['successMessage'] = successMessage
    if name is not None:
        _q['name'] = name
    if email is not None:
        _q['email'] = email
    if body is None:
        raise ValueError("Required request body cannot be null")
    return _ok(_get_client().post("/api/embed/error-page/", body, params=_q or None))


def test_project_alert(organization_slug: str, project_slug: str, alert_id: str, recipient_id: int | None = None):
    """Test Project Alert"""
    _q: dict = {}
    if recipient_id is not None:
        _q['recipient_id'] = recipient_id
    return _ok(_get_client().post(f"/api/0/projects/{organization_slug}/{project_slug}/alerts/{alert_id}/test/", None, params=_q or None))


# ── PUT ──

def comments_update_comment(issue_id: str, comment_id: str, data: dict):
    """Update Comment"""
    _b: dict = {}
    if data is None:
        raise ValueError("Required request field data cannot be null")
    _b['data'] = data
    return _ok(_get_client().put(f"/api/0/issues/{issue_id}/comments/{comment_id}/", _b))


def issues_update_issue(issue_id: str, status: Literal['unresolved', 'resolved', 'ignored'] | None = None, statusDetails: dict | None = None, merge: int | None = None):
    """Update Issue"""
    _b: dict = {}
    if status is not None:
        _b['status'] = status
    if statusDetails is not None:
        _b['statusDetails'] = statusDetails
    if merge is not None:
        _b['merge'] = merge
    return _ok(_get_client().put(f"/api/0/issues/{issue_id}/", _b))


def issues_update_issues(organization_slug: str, id: list[int] | None = None, start: str | None = None, end: str | None = None, project: list[int] | None = None, environment: list[str] | None = None, query: str | None = None, status: Literal['unresolved', 'resolved', 'ignored'] | None = None, statusDetails: dict | None = None, merge: int | None = None):
    """Update Issues"""
    _q: dict = {}
    if id is not None:
        _q['id'] = id
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    if project is not None:
        _q['project'] = project
    if environment is not None:
        _q['environment'] = environment
    if query is not None:
        _q['query'] = query
    _b: dict = {}
    if status is not None:
        _b['status'] = status
    if statusDetails is not None:
        _b['statusDetails'] = statusDetails
    if merge is not None:
        _b['merge'] = merge
    return _ok(_get_client().put(f"/api/0/organizations/{organization_slug}/issues/", _b, params=_q or None))


def issues_update_organization_issue(organization_slug: str, issue_id: str, status: Literal['unresolved', 'resolved', 'ignored'] | None = None, statusDetails: dict | None = None, merge: int | None = None):
    """Update Organization Issue"""
    _b: dict = {}
    if status is not None:
        _b['status'] = status
    if statusDetails is not None:
        _b['statusDetails'] = statusDetails
    if merge is not None:
        _b['merge'] = merge
    return _ok(_get_client().put(f"/api/0/organizations/{organization_slug}/issues/{issue_id}/", _b))


def set_email_as_primary(user_id: str, email: str):
    """Set Email As Primary"""
    _b: dict = {}
    if email is None:
        raise ValueError("Required request field email cannot be null")
    _b['email'] = email
    return _ok(_get_client().put(f"/api/0/users/{user_id}/emails/", _b))


def update_environment_project(organization_slug: str, project_slug: str, name: str, name_body: str, isHidden: bool):
    """Update Environment Project"""
    _b: dict = {}
    if name_body is None:
        raise ValueError("Required request field name cannot be null")
    _b['name'] = name_body
    if isHidden is None:
        raise ValueError("Required request field isHidden cannot be null")
    _b['isHidden'] = isHidden
    return _ok(_get_client().put(f"/api/0/projects/{organization_slug}/{project_slug}/environments/{name}/", _b))


def update_monitor(organization_slug: str, monitor_id: str, expectedBody: str, expectedStatus: int | None, timeout: int | None, name: str, project: str | None = None, monitorType: str | None = None, url: str | None = None, interval: int | None = None):
    """Update Monitor"""
    _b: dict = {}
    if expectedBody is None:
        raise ValueError("Required request field expectedBody cannot be null")
    _b['expectedBody'] = expectedBody
    _b['expectedStatus'] = expectedStatus
    _b['timeout'] = timeout
    if name is None:
        raise ValueError("Required request field name cannot be null")
    _b['name'] = name
    if project is not None:
        _b['project'] = project
    if monitorType is not None:
        _b['monitorType'] = monitorType
    if url is not None:
        _b['url'] = url
    if interval is not None:
        _b['interval'] = interval
    return _ok(_get_client().put(f"/api/0/organizations/{organization_slug}/monitors/{monitor_id}/", _b))


def update_notifications(user_id: str, subscribeByDefault: bool | None = None):
    """Update Notifications"""
    _b: dict = {}
    if subscribeByDefault is not None:
        _b['subscribeByDefault'] = subscribeByDefault
    return _ok(_get_client().put(f"/api/0/users/{user_id}/notifications/", _b))


def update_organization(organization_slug: str, name: str):
    """Update Organization"""
    _b: dict = {}
    if name is None:
        raise ValueError("Required request field name cannot be null")
    _b['name'] = name
    return _ok(_get_client().put(f"/api/0/organizations/{organization_slug}/", _b))


def update_organization_member(organization_slug: str, member_id: str, orgRole: Literal['member', 'admin', 'manager', 'owner'], teamRoles: list[dict] | None = None):
    """Update Organization Member"""
    _b: dict = {}
    if orgRole is None:
        raise ValueError("Required request field orgRole cannot be null")
    _b['orgRole'] = orgRole
    if teamRoles is not None:
        _b['teamRoles'] = teamRoles
    return _ok(_get_client().put(f"/api/0/organizations/{organization_slug}/members/{member_id}/", _b))


def update_project(organization_slug: str, project_slug: str, name: str, slug: str | None = None, platform: str | None = None, eventThrottleRate: int | None = None):
    """Update Project"""
    _b: dict = {}
    if name is None:
        raise ValueError("Required request field name cannot be null")
    _b['name'] = name
    if slug is not None:
        _b['slug'] = slug
    if platform is not None:
        _b['platform'] = platform
    if eventThrottleRate is not None:
        _b['eventThrottleRate'] = eventThrottleRate
    return _ok(_get_client().put(f"/api/0/projects/{organization_slug}/{project_slug}/", _b))


def update_project_alert(organization_slug: str, project_slug: str, alert_id: str, name: str | None = None, alertRecipients: list[dict] | None = None, timespanMinutes: int | None = None, quantity: int | None = None, uptime: bool | None = None):
    """Update Project Alert"""
    _b: dict = {}
    if name is not None:
        _b['name'] = name
    if alertRecipients is not None:
        _b['alertRecipients'] = alertRecipients
    if timespanMinutes is not None:
        _b['timespanMinutes'] = timespanMinutes
    if quantity is not None:
        _b['quantity'] = quantity
    if uptime is not None:
        _b['uptime'] = uptime
    return _ok(_get_client().put(f"/api/0/projects/{organization_slug}/{project_slug}/alerts/{alert_id}/", _b))


def update_project_key(organization_slug: str, project_slug: str, key_id: str, name: str | None = None, rateLimit: dict | None = None):
    """Update Project Key"""
    _b: dict = {}
    if name is not None:
        _b['name'] = name
    if rateLimit is not None:
        _b['rateLimit'] = rateLimit
    return _ok(_get_client().put(f"/api/0/projects/{organization_slug}/{project_slug}/keys/{key_id}/", _b))


def update_project_release(organization_slug: str, project_slug: str, version: str, ref: str | None = None, dateReleased: str | None = None):
    """Update Project Release"""
    _b: dict = {}
    if ref is not None:
        _b['ref'] = ref
    if dateReleased is not None:
        _b['dateReleased'] = dateReleased
    return _ok(_get_client().put(f"/api/0/projects/{organization_slug}/{project_slug}/releases/{version}/", _b))


def update_release(organization_slug: str, version: str, ref: str | None = None, dateReleased: str | None = None):
    """Update Release"""
    _b: dict = {}
    if ref is not None:
        _b['ref'] = ref
    if dateReleased is not None:
        _b['dateReleased'] = dateReleased
    return _ok(_get_client().put(f"/api/0/organizations/{organization_slug}/releases/{version}/", _b))


def update_team(organization_slug: str, team_slug: str, slug: str):
    """Update Team"""
    _b: dict = {}
    if slug is None:
        raise ValueError("Required request field slug cannot be null")
    _b['slug'] = slug
    return _ok(_get_client().put(f"/api/0/teams/{organization_slug}/{team_slug}/", _b))


def update_user(user_id: str, options: dict, name: str | None = None):
    """Update User"""
    _b: dict = {}
    if options is None:
        raise ValueError("Required request field options cannot be null")
    _b['options'] = options
    if name is not None:
        _b['name'] = name
    return _ok(_get_client().put(f"/api/0/users/{user_id}/", _b))


def update_user_notification_alerts(user_id: str, body: dict | list):
    """Update User Notification Alerts"""
    if body is None:
        raise ValueError("Required request body cannot be null")
    return _ok(_get_client().put(f"/api/0/users/{user_id}/notifications/alerts/", body))


# ── DELETE ──

def comments_delete_comment(issue_id: str, comment_id: str):
    """Delete Comment"""
    return _ok(_get_client().delete(f"/api/0/issues/{issue_id}/comments/{comment_id}/"))


def delete_api_token(token_id: str):
    """Delete Api Token"""
    return _ok(_get_client().delete(f"/api/0/api-tokens/{token_id}/"))


def delete_email(user_id: str, email: str):
    """Delete Email"""
    _b: dict = {}
    if email is None:
        raise ValueError("Required request field email cannot be null")
    _b['email'] = email
    return _ok(_get_client().delete(f"/api/0/users/{user_id}/emails/", _b))


def delete_member_from_team(organization_slug: str, member_id: str, team_slug: str):
    """Delete Member From Team"""
    return _ok(_get_client().delete(f"/api/0/organizations/{organization_slug}/members/{member_id}/teams/{team_slug}/"))


def delete_monitor(organization_slug: str, monitor_id: str):
    """Delete Monitor"""
    return _ok(_get_client().delete(f"/api/0/organizations/{organization_slug}/monitors/{monitor_id}/"))


def delete_organization(organization_slug: str):
    """Delete Organization"""
    return _ok(_get_client().delete(f"/api/0/organizations/{organization_slug}/"))


def delete_organization_member(organization_slug: str, member_id: str):
    """Delete Organization Member"""
    return _ok(_get_client().delete(f"/api/0/organizations/{organization_slug}/members/{member_id}/"))


def delete_organization_release(organization_slug: str, version: str):
    """Delete Organization Release"""
    return _ok(_get_client().delete(f"/api/0/organizations/{organization_slug}/releases/{version}/"))


def delete_organization_release_file(organization_slug: str, version: str, file_id: str):
    """Delete Organization Release File"""
    return _ok(_get_client().delete(f"/api/0/organizations/{organization_slug}/releases/{version}/files/{file_id}/"))


def delete_project(organization_slug: str, project_slug: str):
    """Delete Project"""
    return _ok(_get_client().delete(f"/api/0/projects/{organization_slug}/{project_slug}/"))


def delete_project_alert(organization_slug: str, project_slug: str, alert_id: str):
    """Delete Project Alert"""
    return _ok(_get_client().delete(f"/api/0/projects/{organization_slug}/{project_slug}/alerts/{alert_id}/"))


def delete_project_key(organization_slug: str, project_slug: str, key_id: str):
    """Delete Project Key"""
    return _ok(_get_client().delete(f"/api/0/projects/{organization_slug}/{project_slug}/keys/{key_id}/"))


def delete_project_release(organization_slug: str, project_slug: str, version: str):
    """Delete Project Release"""
    return _ok(_get_client().delete(f"/api/0/projects/{organization_slug}/{project_slug}/releases/{version}/"))


def delete_project_release_file(organization_slug: str, project_slug: str, version: str, file_id: str):
    """Delete Project Release File"""
    return _ok(_get_client().delete(f"/api/0/projects/{organization_slug}/{project_slug}/releases/{version}/files/{file_id}/"))


def delete_team(organization_slug: str, team_slug: str):
    """Delete Team"""
    return _ok(_get_client().delete(f"/api/0/teams/{organization_slug}/{team_slug}/"))


def delete_team_from_project(organization_slug: str, project_slug: str, team_slug: str):
    """Delete Team From Project"""
    return _ok(_get_client().delete(f"/api/0/projects/{organization_slug}/{project_slug}/teams/{team_slug}/"))


def delete_user(user_id: str):
    """Delete User"""
    return _ok(_get_client().delete(f"/api/0/users/{user_id}/"))


def hashes_delete_hash(organization_slug: str, issue_id: str, id: list[str]):
    """Delete Hash"""
    _q: dict = {}
    if id is not None:
        _q['id'] = id
    return _ok(_get_client().delete(f"/api/0/organizations/{organization_slug}/issues/{issue_id}/hashes/", params=_q or None))


def issues_delete_issue(issue_id: str):
    """Delete Issue"""
    return _ok(_get_client().delete(f"/api/0/issues/{issue_id}/"))


def issues_delete_issues(organization_slug: str, id: list[int] | None = None, start: str | None = None, end: str | None = None, project: list[int] | None = None, environment: list[str] | None = None, query: str | None = None):
    """Delete Issues"""
    _q: dict = {}
    if id is not None:
        _q['id'] = id
    if start is not None:
        _q['start'] = start
    if end is not None:
        _q['end'] = end
    if project is not None:
        _q['project'] = project
    if environment is not None:
        _q['environment'] = environment
    if query is not None:
        _q['query'] = query
    return _ok(_get_client().delete(f"/api/0/organizations/{organization_slug}/issues/", params=_q or None))


def setup_wizard_delete(wizard_hash: str, auth: str | None = None):
    """Setup Wizard Delete"""
    _q: dict = {}
    if auth is not None:
        _q['auth'] = auth
    return _ok(_get_client().delete(f"/api/0/wizard/{wizard_hash}/", params=_q or None))
